version: '3'
services:
  web:
    container_name: nginx-container
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./src:/var/www/rails-app"
      - "./container-config/nginx/rails.conf:/etc/nginx/conf.d/default.conf"
      - "./container-config/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./persist-data/web-logs:/var/log/nginx"
    depends_on:
      - app
    networks:
      docker-network:
        ipv4_address: 172.22.0.8

  mariadb:
    container_name: mariadb-container
    image: mariadb:latest
    volumes:
      - "./persist-data/db-data:/var/lib/mysql"
      - "./container-config/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf"
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
    expose:
      - "3306"
    networks:
      docker-network:
        ipv4_address: 172.22.0.10

  app:
    container_name: rails-container
    build:
      context: .
      dockerfile: ./container-dockerfile/app-server/Dockerfile
    volumes:
      - ./src:/var/www/rails-app
      - "./container-config/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "./container-config/rails-app/database.yml:/var/www/rails-app/config/database.yml"
    environment:
      - RAILS_DB_HOST=mariadb
      - RAILS_DB_USER=root
      - RAILS_DB_PASSWORD=mariadb
    expose:
     - "3000"
    depends_on:
      - mariadb
    command: >
      rails s -p 3000 -b '0.0.0.0'
    networks:
      docker-network:
        ipv4_address: 172.22.0.2

  chrome:
    container_name: chrome-container
    image: selenium/standalone-chrome-debug:3.141.59-hafnium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
      - 5900:5900
    networks:
      docker-network:
        ipv4_address: 172.22.0.3

  phpmyadmin:
    container_name: phpmyadmin-container
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=mariadb
    ports:
       - 8000:80
    volumes:
       - "./persist-data/phpmyadmin-sessions:/sessions"
    networks:
      docker-network:
        ipv4_address: 172.22.0.4
    depends_on:
      - mariadb

networks:
  docker-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.22.0.0/24
